// Pure contracts for fleet synchronization of the centrally managed .codex
// files. Network orchestration lives in ../sync-codex.mjs; this module keeps
// content comparison, manifest selection, and stable-branch decisions
// deterministic and unit-testable.

import { createHash } from 'node:crypto';
import { readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { GOVERNED_CODEX_FILES } from './baseline-files.mjs';

export const CODEX_SYNC_BRANCH = 'governance/codex-sync';
export const CODEX_SYNC_BOT = 'qwts-codex-agent';
export const CODEX_SOURCE_REPO = 'playbook-engineering';
export const CODEX_SYNC_TITLE = 'governance: sync managed .codex files';
export const CODEX_SYNC_COMMIT_PREFIX = `governance: sync .codex from ${CODEX_SOURCE_REPO}@`;

export function gitBlobSha(content) {
  const bytes = Buffer.isBuffer(content) ? content : Buffer.from(content);
  return createHash('sha1')
    .update(`blob ${bytes.length}\0`)
    .update(bytes)
    .digest('hex');
}

export function loadCanonicalFiles(root, paths = GOVERNED_CODEX_FILES) {
  return new Map(paths.map((path) => {
    const absolute = join(root, path);
    const content = readFileSync(absolute);
    const executable = (statSync(absolute).mode & 0o111) !== 0;
    return [path, {
      path,
      content,
      sha: gitBlobSha(content),
      mode: executable ? '100755' : '100644',
    }];
  }));
}

export function managedCodexPaths(entry, paths = GOVERNED_CODEX_FILES) {
  if (entry.codexSync?.enabled === false) return [];
  const excluded = new Set(entry.codexSync?.exclude ?? []);
  return paths.filter((path) => !excluded.has(path));
}

export function treeByPath(tree) {
  return new Map(
    (tree ?? [])
      .filter((entry) => entry.type === 'blob')
      .map((entry) => [entry.path, entry]),
  );
}

export function diffManagedFiles(canonicalFiles, targetTree, managedPaths) {
  const target = targetTree instanceof Map ? targetTree : treeByPath(targetTree);
  return managedPaths
    .filter((path) => {
      const source = canonicalFiles.get(path);
      const current = target.get(path);
      return !current || current.sha !== source.sha || current.mode !== source.mode;
    })
    .map((path) => canonicalFiles.get(path));
}

export function chooseSyncHead({ baseSha, branchSha, branchOwned = false, pulls }) {
  const branchPulls = (pulls ?? []).filter((pull) => pull.head?.ref === CODEX_SYNC_BRANCH);
  if (branchPulls.some((pull) => pull.title !== CODEX_SYNC_TITLE)) {
    throw new Error(`${CODEX_SYNC_BRANCH} is attached to a non-sync pull request`);
  }
  const open = branchPulls.filter((pull) => pull.state === 'open');
  if (open.length > 1) {
    throw new Error(`multiple open ${CODEX_SYNC_BRANCH} pull requests found`);
  }
  if (open.length === 1) {
    if (!branchSha) throw new Error(`open sync pull request #${open[0].number} has no branch ref`);
    return { parentSha: branchSha, pull: open[0], resetBranch: false };
  }
  if (branchSha && branchPulls.length === 0 && !branchOwned) {
    throw new Error(`refusing to reset unowned branch ${CODEX_SYNC_BRANCH}`);
  }
  return { parentSha: baseSha, pull: null, resetBranch: Boolean(branchSha) };
}

export function syncPullBody({ owner, sourceSha, paths }) {
  const sourceUrl = `https://github.com/${owner}/${CODEX_SOURCE_REPO}/commit/${sourceSha}`;
  const managed = paths.map((path) => `- \`${path}\``).join('\n');
  return [
    `Synchronizes the centrally managed \`.codex/\` environment from [\`${sourceSha.slice(0, 12)}\`](${sourceUrl}).`,
    '',
    'Managed files:',
    '',
    managed,
    '',
    `Generated by \`node tools/repos/sync-codex.mjs --apply\` for ${owner}/${CODEX_SOURCE_REPO}#60.`,
    'This pull request is bot-authored, requires the target repository checks and review, and never writes to the default branch directly.',
  ].join('\n');
}
